name: Compilation LaTeX
on:
  push:
    branches: [ "main" ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Prepare Git information
        run: |
          # https://mirrors.ircam.fr/pub/CTAN/macros/latex/contrib/gitinfo2/post-xxx-sample.txt
          # Copyright 2015 Brent Longborough
          # Part of gitinfo2 package Version 2
          # Release 2.0.7 2015-11-22
          # Please read gitinfo2.pdf for licencing and other details
          # -----------------------------------------------------
          # Post-{commit,checkout,merge} hook for the gitinfo2 package
          #
          # Get the first tag found in the history from the current HEAD
          FIRSTTAG=$(git describe --tags --always --dirty='-*' 2>/dev/null)
          # Get the first tag in history that looks like a Release
          RELTAG=$(git describe --tags --long --always --dirty='-*' --match '[0-9]*.*' 2>/dev/null)
          # Hoover up the metadata
          git --no-pager log -1 --date=short --decorate=short \
          --pretty=format:"\usepackage[%
          shash={%h},
          lhash={%H},
          authname={%an},
          authemail={%ae},
          authsdate={%ad},
          authidate={%ai},
          authudate={%at},
          commname={%cn},
          commemail={%ce},
          commsdate={%cd},
          commidate={%ci},
          commudate={%ct},
          refnames={%d},
          firsttagdescribe={$FIRSTTAG},
          reltag={$RELTAG}
          ]{gitexinfo}" HEAD > .git/gitHeadInfo.gin

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: math-ulm-2023.tex
          compiler: latexmk
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -bibtex
      - name: Upload PDF file
        run: |
          # see https://docs.gitlab.com/ee/ci/ssh_keys/
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          scp math-ulm-2023.pdf ${{ secrets.SSH_DEPLOY_PATH }}
